POST http://localhost:8080/acolhe/clinicas/adicionar
Content-Type: application/json

{
  "nmClinica": "tegte api",
  "email": "api@example.com",
  "telefone": "1234567890",
  "descricao": "hahahahaah",
  "imagem": "URL da Imagem",
  "bairro": "Bairro",
  "cidade": "Cidade",
  "nmEstado": "Nome do Estado",
  "sgEstado": "sp",
  "patrocinada": true
}
