POST http://localhost:8080/acolhe/clinicas/adicionar
Content-Type: application/json

{
  "nmClinica": "tee adssa",
  "email": "api@exalse.ascom",
  "telefone": "12367122890",
  "descricao": "hahahahaah",
  "imagem": "URL da Imagem",
  "bairro": "Bairro",
  "cidade": "Cidade",
  "nmEstado": "Nome do Estado",
  "sgEstado": "sp",
  "patrocinada": true
}
