# Deploy da API (Back-End) do projeto via Pipeline
# Para testes, será utilizado na branch DEV
# Somente na branch "PROD", por se tratar justamente do ambiente de produção.
# Acesso em https://api-acolhe.onrender.com
# Matplace utilizado: Render Deploy Action by johnbeynon
# Secrets adicionados, por boas práticas Devops e Fidelidade dos Dados

name: Deploy API-Acolhe

on: 
  push:
    branches: [ "DEV"  ]
  pull_request:
    branches: [ "DEV"  ]
    
jobs:
  
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy automático no render
      uses: johnbeynon/render-deploy-action@v0.0.8
      with:
        service-id: ${{ secrets.SERVICE_ID }}
        api-key: ${{ secrets.API_KEY }}
